import AllNewRush from "../assets/cars/all-new-rush.png";
import AllNewTerios from "../assets/cars/all-new-terios.png";
import CRV from "../assets/cars/cr-v.png";
import CRVBLack from "../assets/cars/cr-v-black.png";
import Koenigsegg from "../assets/cars/koenigsegg.png";
import NewMgZS from "../assets/cars/new-mg-zs.png";
import NewMGExclusive from "../assets/cars/mg-zx-exclusice.png";
import NissanGTR from "../assets/cars/nissan-gt-r.png";
import RollsRoyce from "../assets/cars/rolls-royce.png";

const carData = [
  {
    id: 1,
    image: Koenigsegg,
    name: "Koenigsegg",
    type: "Sport",
    price: "$99.00",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "2 People",
    isFavorite: false,
  },
  {
    id: 2,
    image: NissanGTR,
    name: "Nissan GT-R",
    type: "Sport",
    price: "$80.00",
    oldPrice: "$100.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    isFavorite: true,
  },
  {
    id: 3,
    image: RollsRoyce,
    name: "Rolls-Royce",
    type: "Sedan",
    price: "$96.00",
    oldPrice: "$100.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    isFavorite: true,
  },
  {
    id: 4,
    image: NissanGTR,
    name: "Nissan GT-R",
    type: "Sport",
    price: "$90.00",
    oldPrice: "$100.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    isFavorite: true,
  },
  {
    id: 5,
    image: AllNewRush,
    name: "All New Rush",
    type: "SUV",
    price: "$72.00",
    oldPrice: "$80.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: false,
  },
  {
    id: 6,
    image: AllNewTerios,
    name: "All New Terios",
    type: "SUV",
    price: "$74.00",
    oldPrice: "$85.00",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "6 People",
    isFavorite: true,
  },
  {
    id: 7,
    image: CRV,
    name: "CR - V",
    type: "SUV",
    price: "$80.00",
    oldPrice: "$100.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: true,
  },
  {
    id: 8,
    image: CRVBLack,
    name: "MG ZX Excite",
    type: "SUV",
    price: "$80.00",
    oldPrice: "$100.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: false,
  },
  {
    id: 9,
    image: NewMgZS,
    name: "New Mg ZS",
    type: "SUV",
    price: "$82.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: false,
  },
  {
    id: 10,
    image: NewMGExclusive,
    name: "MG ZX Exclusive",
    type: "SUV",
    price: "$85.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: true,
  },
  {
    id: 11,
    image: NewMgZS,
    name: "New Mg ZS",
    type: "SUV",
    price: "$82.00",
    oldPrice: "$105.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: true,
  },
  {
    id: 12,
    image: NewMGExclusive,
    name: "MG ZX Exclusive",
    type: "SUV",
    price: "$85.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: false,
  },
  {
    id: 13,
    image: NewMgZS,
    name: "New Mg ZS",
    type: "SUV",
    price: "$82.00",
    oldPrice: "$105.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    isFavorite: true,
  },
];

export default carData;
